version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm i
      - run: npm run test
      - run: npm run pack

workflows:
  version: 2
  uxi-b:
    jobs:
      - test
